const SUPABASE_URL = "https://pvequwqgayemqedtbfzn.supabase.co"; 
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2ZXF1d3FnYXllbXFlZHRiZnpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1NTgwODYsImV4cCI6MjA4ODEzNDA4Nn0.jLVX4hezSdb5mgAx2GdIg5P4n8BnWb5fkhWcyeNmGOM"; 

export const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);